/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckBookingRouteImport } from './routes/check-booking'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffSignupRouteImport } from './routes/staff.signup'
import { Route as RoomsRoomTypeIdRouteImport } from './routes/rooms.$roomTypeId'
import { Route as AdminStoriesRouteImport } from './routes/admin/stories'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminRoomTypesRouteImport } from './routes/admin/room-types'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGuestsRouteImport } from './routes/admin/guests'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminApproveStaffRouteImport } from './routes/admin/approve-staff'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckBookingRoute = CheckBookingRouteImport.update({
  id: '/check-booking',
  path: '/check-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StaffSignupRoute = StaffSignupRouteImport.update({
  id: '/staff/signup',
  path: '/staff/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomTypeIdRoute = RoomsRoomTypeIdRouteImport.update({
  id: '/$roomTypeId',
  path: '/$roomTypeId',
  getParentRoute: () => RoomsRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomTypesRoute = AdminRoomTypesRouteImport.update({
  id: '/room-types',
  path: '/room-types',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuestsRoute = AdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApproveStaffRoute = AdminApproveStaffRouteImport.update({
  id: '/approve-staff',
  path: '/approve-staff',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/check-booking': typeof CheckBookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/approve-staff': typeof AdminApproveStaffRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/room-types': typeof AdminRoomTypesRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/rooms/$roomTypeId': typeof RoomsRoomTypeIdRoute
  '/staff/signup': typeof StaffSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/check-booking': typeof CheckBookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/approve-staff': typeof AdminApproveStaffRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/room-types': typeof AdminRoomTypesRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/rooms/$roomTypeId': typeof RoomsRoomTypeIdRoute
  '/staff/signup': typeof StaffSignupRoute
  '/admin': typeof AdminIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/check-booking': typeof CheckBookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/approve-staff': typeof AdminApproveStaffRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/room-types': typeof AdminRoomTypesRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/rooms/$roomTypeId': typeof RoomsRoomTypeIdRoute
  '/staff/signup': typeof StaffSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/booking'
    | '/booking-confirmation'
    | '/check-booking'
    | '/contact'
    | '/dashboard'
    | '/rooms'
    | '/search'
    | '/signin'
    | '/signup'
    | '/admin/approve-staff'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/room-types'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/stories'
    | '/rooms/$roomTypeId'
    | '/staff/signup'
    | '/admin/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/booking-confirmation'
    | '/check-booking'
    | '/contact'
    | '/dashboard'
    | '/search'
    | '/signin'
    | '/signup'
    | '/admin/approve-staff'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/room-types'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/stories'
    | '/rooms/$roomTypeId'
    | '/staff/signup'
    | '/admin'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/booking'
    | '/booking-confirmation'
    | '/check-booking'
    | '/contact'
    | '/dashboard'
    | '/rooms'
    | '/search'
    | '/signin'
    | '/signup'
    | '/admin/approve-staff'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/room-types'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/stories'
    | '/rooms/$roomTypeId'
    | '/staff/signup'
    | '/admin/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  CheckBookingRoute: typeof CheckBookingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  StaffSignupRoute: typeof StaffSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-booking': {
      id: '/check-booking'
      path: '/check-booking'
      fullPath: '/check-booking'
      preLoaderRoute: typeof CheckBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/staff/signup': {
      id: '/staff/signup'
      path: '/staff/signup'
      fullPath: '/staff/signup'
      preLoaderRoute: typeof StaffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomTypeId': {
      id: '/rooms/$roomTypeId'
      path: '/$roomTypeId'
      fullPath: '/rooms/$roomTypeId'
      preLoaderRoute: typeof RoomsRoomTypeIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/room-types': {
      id: '/admin/room-types'
      path: '/room-types'
      fullPath: '/admin/room-types'
      preLoaderRoute: typeof AdminRoomTypesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guests': {
      id: '/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AdminGuestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/approve-staff': {
      id: '/admin/approve-staff'
      path: '/approve-staff'
      fullPath: '/admin/approve-staff'
      preLoaderRoute: typeof AdminApproveStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApproveStaffRoute: typeof AdminApproveStaffRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGuestsRoute: typeof AdminGuestsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoomTypesRoute: typeof AdminRoomTypesRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApproveStaffRoute: AdminApproveStaffRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGuestsRoute: AdminGuestsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoomTypesRoute: AdminRoomTypesRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface RoomsRouteChildren {
  RoomsRoomTypeIdRoute: typeof RoomsRoomTypeIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomTypeIdRoute: RoomsRoomTypeIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  CheckBookingRoute: CheckBookingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  StaffSignupRoute: StaffSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
